#!/usr/bin/bash
# Run from this directory.
cd ${0%/*} || exit 1    

# Source tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set the number of processors.
NUM_PROCESSORS=4

# Choose the grid mesh.
GRID_FILENAME=porous_mesh.stl

# Run a command and check its exit code.
run_and_check() {
    runApplication $1 $2

    if ! [ $? = 0 ];
    then
        echo "$1 failed!"
        exit 1
    fi
}

# Run a command in parallel and check its exit code.
run_and_check_parallel() {
    runParallel -np $NUM_PROCESSORS $1 $2

    if ! [ $? = 0 ];
    then
        echo "$1 failed!"
        exit 1
    fi
}

run_and_check blockMesh

run_and_check checkMesh

cp ../exported-meshes/$GRID_FILENAME constant/geometry/grid.stl
if ! [ $? = 0 ];
then
    echo "Copying the grid mesh failed!"
    exit 1
fi

run_and_check surfaceFeatures

run_and_check snappyHexMesh -overwrite

run_and_check decomposePar -copyZero

run_and_check_parallel renumberMesh -overwrite

run_and_check_parallel potentialFoam -initialiseUBCs

run_and_check_parallel $(getApplication)

paraFoam -touch
for (( i=0; i<$NUM_PROCESSORS; ++i )); 
do 
    cd processor$i
    paraFoam -touch
    cd ..
done

#------------------------------------------------------------------------------