#!/usr/bin/bash
# Run from this directory.
cd ${0%/*} || exit 1    

# Source tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Check the number of processors.
NUM_PROCESSORS=$(python3 extract_num_processors.py 2>&1)
if ! [ $? = 0 ];
then
    echo "Extraction of number of processors failed!"
    exit 1
fi
if ! [ $NUM_PROCESSORS = 1 ];
then
    echo "Error! The domain must not be composed for a serial run!"
    exit 1
fi

# Run a command and check its exit code.
run_and_check() {
    runApplication $1 $2

    if ! [ $? = 0 ];
    then
        echo "$1 failed!"
        exit 1
    fi
}

run_and_check surfaceFeatureExtract

run_and_check blockMesh

run_and_check snappyHexMesh -overwrite

run_and_check restore0Dir

run_and_check potentialFoam -writephi

run_and_check $(getApplication)

paraFoam -touch

python3 compute_pressure_drop.py
if ! [ $? = 0 ];
then
    echo "Computation of pressure drop coefficient failed!"
    exit 1
fi

# Sound notification.
# Might be useful if you want to be notified when the simulation is done.
# paplay /usr/share/sounds/freedesktop/stereo/complete.oga

#------------------------------------------------------------------------------